# Regresion Lineal en Python

## El paquete Scikit Learn para la regresion lineal y la seleccion de rasgos

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import numpy as np
import pandas as pd

In [2]:
data= pd.read_csv(r"C:\Users\Asus\Desktop\Datasets\datasets\ads\Advertising.csv")

In [3]:
feature_cols = ["TV","Radio","Newspaper"]

In [4]:
x = data[feature_cols]
y = data["Sales"]

In [6]:
estimator = SVR(kernel = "linear")
selector = RFE(estimator, 2 , step=1)
selector.fit(x,y)

RFE(estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
                  gamma='auto_deprecated', kernel='linear', max_iter=-1,
                  shrinking=True, tol=0.001, verbose=False),
    n_features_to_select=2, step=1, verbose=0)

In [7]:
selector.support_

array([ True,  True, False])

In [8]:
selector.ranking_

array([1, 1, 2])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
X_pred = data[["TV","Radio"]]

In [13]:
lm = LinearRegression()

In [15]:
lm.fit(X_pred, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
lm.coef_

array([0.04575482, 0.18799423])

In [17]:
lm.intercept_

2.921099912405138

In [18]:
lm.score(X_pred,y)

0.8971942610828956